# Generated by Django 3.0.7 on 2020-08-03 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 17, 48, 23, 300378, tzinfo=utc), verbose_name='Publiced Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 17, 48, 23, 301087, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
