# Generated by Django 3.0.7 on 2020-08-03 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200803_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 17, 58, 5, 926290, tzinfo=utc), verbose_name='Publiced Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 17, 58, 5, 926920, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
