# Generated by Django 3.0.5 on 2020-08-06 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200804_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 4, 54, 21, 670369, tzinfo=utc), verbose_name='Publiced Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 4, 54, 21, 672369, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
