# Generated by Django 3.1.6 on 2021-02-28 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200806_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 15, 19, 52, 966728, tzinfo=utc), verbose_name='Publiced Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 15, 19, 52, 967426, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
