# Generated by Django 3.0.7 on 2020-08-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clasy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='welayat',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Which welayat'),
        ),
    ]
