# Generated by Django 3.0.7 on 2020-08-02 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200802_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 14, 44, 48, 999603, tzinfo=utc), verbose_name='Comment pubdate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comnum',
            field=models.IntegerField(default=0, verbose_name='Comment number'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 14, 44, 48, 998854, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
