# Generated by Django 3.0.7 on 2020-08-02 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200802_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 14, 45, 44, 613245, tzinfo=utc), verbose_name='Comment pubdate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='preview',
            field=models.CharField(default='', max_length=50, verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 14, 45, 44, 612561, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
