# Generated by Django 3.0.7 on 2020-08-02 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200802_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 14, 46, 58, 221639, tzinfo=utc), verbose_name='Comment pubdate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='preview',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 14, 46, 58, 221018, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
