# Generated by Django 3.0.7 on 2020-08-03 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200802_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='actual',
            field=models.IntegerField(default=3, verbose_name='How many correct answers'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 9, 55, 21, 635226, tzinfo=utc), verbose_name='Comment pubdate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 9, 55, 21, 634538, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
