# Generated by Django 3.0.7 on 2020-08-03 09:58

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_auto_20200803_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 9, 58, 8, 891574, tzinfo=utc), verbose_name='Comment pubdate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 9, 58, 8, 890223, tzinfo=utc), verbose_name='Publiced Date'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='solver',
        ),
        migrations.AddField(
            model_name='question',
            name='solver',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
