# Generated by Django 3.0.7 on 2020-08-03 10:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0007_auto_20200803_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 10, 10, 51, 639380, tzinfo=utc), verbose_name='Comment pubdate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 10, 10, 51, 638658, tzinfo=utc), verbose_name='Publiced Date'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='solver',
        ),
        migrations.AddField(
            model_name='question',
            name='solver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
