# Generated by Django 3.0.7 on 2020-08-03 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20200803_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 10, 14, 49, 206155, tzinfo=utc), verbose_name='Comment pubdate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 10, 14, 49, 205430, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
