# Generated by Django 3.0.7 on 2020-08-03 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20200803_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 17, 58, 5, 925448, tzinfo=utc), verbose_name='Comment pubdate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 17, 58, 5, 924816, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
