# Generated by Django 3.0.7 on 2020-08-04 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20200803_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 7, 32, 52, 53626, tzinfo=utc), verbose_name='Comment pubdate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='actual',
            field=models.IntegerField(default=0, verbose_name='How many correct answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 7, 32, 52, 52984, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
