# Generated by Django 3.1.6 on 2021-02-28 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20200806_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 15, 19, 52, 965935, tzinfo=utc), verbose_name='Comment pubdate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 15, 19, 52, 965297, tzinfo=utc), verbose_name='Publiced Date'),
        ),
    ]
